on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: coreangcosmosregistry.azurecr.io
        username: ${{ secrets.acr_coreangcosmosregistry_username }}
        password: ${{ secrets.acr_coreangcosmosregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/CoreAngCosmos" -f  "CoreAngCosmos/CoreAngCosmos.API/Dockerfile" -t coreangcosmosregistry.azurecr.io/coreangcosmosaks:${{ github.sha }}
        docker push coreangcosmosregistry.azurecr.io/coreangcosmosaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_coreangcosmosaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep coreangcosmosaks6927 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace coreangcosmosaks6927`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: coreangcosmosaks6927
        container-registry-url: coreangcosmosregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_coreangcosmosregistry_username }}
        container-registry-password: ${{ secrets.acr_coreangcosmosregistry_password }}
        secret-name: coreangcosmodockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: coreangcosmosaks6927
        manifests: |
          manifests/deployment-3.yml
          manifests/service-3.yml
          manifests/ingress.yml
        images: |
          coreangcosmosregistry.azurecr.io/coreangcosmosaks:${{ github.sha }}
        imagepullsecrets: |
          coreangcosmodockerauth