on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: coreangcosmosapi.azurecr.io
        username: ${{ secrets.acr_coreangcosmosapi_username }}
        password: ${{ secrets.acr_coreangcosmosapi_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/CoreAngCosmos/CoreAngCosmos.API" -f  "CoreAngCosmos/CoreAngCosmos.API/Dockerfile" -t coreangcosmosapi.azurecr.io/coreangcosmoskubernetes:${{ github.sha }}
        docker push coreangcosmosapi.azurecr.io/coreangcosmoskubernetes:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_coreangcosmoskubernetes_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep coreangcosmoskuberneteseb49 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace coreangcosmoskuberneteseb49`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: coreangcosmoskuberneteseb49
        container-registry-url: coreangcosmosapi.azurecr.io
        container-registry-username: ${{ secrets.acr_coreangcosmosapi_username }}
        container-registry-password: ${{ secrets.acr_coreangcosmosapi_password }}
        secret-name: coreangcosmodockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: coreangcosmoskuberneteseb49
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          coreangcosmosapi.azurecr.io/coreangcosmoskubernetes:${{ github.sha }}
        imagepullsecrets: |
          coreangcosmodockerauth